const scores = [
  {
    id: "messico-sudafrica",
    homeTeam: "Messico",
    awayTeam: "Sudafrica",
    apiHomeTeam: "Mexico",
    apiAwayTeam: "South Africa",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "corea-del-sud-cechia",
    homeTeam: "Corea del Sud",
    awayTeam: "Cechia",
    apiHomeTeam: "South Korea",
    apiAwayTeam: "Czech Republic",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "canada-bosnia-ed-erzegovina",
    homeTeam: "Canada",
    awayTeam: "Bosnia ed Erzegovina",
    apiHomeTeam: "Canada",
    apiAwayTeam: "Bosnia and Herzegovina",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "svizzera-qatar",
    homeTeam: "Svizzera",
    awayTeam: "Qatar",
    apiHomeTeam: "Switzerland",
    apiAwayTeam: "Qatar",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "stati-uniti-paraguay",
    homeTeam: "Stati Uniti",
    awayTeam: "Paraguay",
    apiHomeTeam: "United States",
    apiAwayTeam: "Paraguay",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "brasile-marocco",
    homeTeam: "Brasile",
    awayTeam: "Marocco",
    apiHomeTeam: "Brazil",
    apiAwayTeam: "Morocco",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "haiti-scozia",
    homeTeam: "Haiti",
    awayTeam: "Scozia",
    apiHomeTeam: "Haiti",
    apiAwayTeam: "Scotland",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "australia-turchia",
    homeTeam: "Australia",
    awayTeam: "Turchia",
    apiHomeTeam: "Australia",
    apiAwayTeam: "Turkey",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "germania-curacao",
    homeTeam: "Germania",
    awayTeam: "Curaçao",
    apiHomeTeam: "Germany",
    apiAwayTeam: "Curacao",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "paesi-bassi-giappone",
    homeTeam: "Paesi Bassi",
    awayTeam: "Giappone",
    apiHomeTeam: "Netherlands",
    apiAwayTeam: "Japan",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "costa-davorio-ecuador",
    homeTeam: "Costa d’Avorio",
    awayTeam: "Ecuador",
    apiHomeTeam: "Ivory Coast",
    apiAwayTeam: "Ecuador",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "svezia-tunisia",
    homeTeam: "Svezia",
    awayTeam: "Tunisia",
    apiHomeTeam: "Sweden",
    apiAwayTeam: "Tunisia",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "belgio-egitto",
    homeTeam: "Belgio",
    awayTeam: "Egitto",
    apiHomeTeam: "Belgium",
    apiAwayTeam: "Egypt",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "spagna-capo-verde",
    homeTeam: "Spagna",
    awayTeam: "Capo Verde",
    apiHomeTeam: "Spain",
    apiAwayTeam: "Cape Verde",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "iran-nuova-zelanda",
    homeTeam: "Iran",
    awayTeam: "Nuova Zelanda",
    apiHomeTeam: "Iran",
    apiAwayTeam: "New Zealand",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "arabia-saudita-uruguay",
    homeTeam: "Arabia Saudita",
    awayTeam: "Uruguay",
    apiHomeTeam: "Saudi Arabia",
    apiAwayTeam: "Uruguay",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "francia-senegal",
    homeTeam: "Francia",
    awayTeam: "Senegal",
    apiHomeTeam: "France",
    apiAwayTeam: "Senegal",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "iraq-norvegia",
    homeTeam: "Iraq",
    awayTeam: "Norvegia",
    apiHomeTeam: "Iraq",
    apiAwayTeam: "Norway",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "argentina-algeria",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    apiHomeTeam: "Argentina",
    apiAwayTeam: "Algeria",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "austria-giordania",
    homeTeam: "Austria",
    awayTeam: "Giordania",
    apiHomeTeam: "Austria",
    apiAwayTeam: "Jordan",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "portogallo-congo",
    homeTeam: "Portogallo",
    awayTeam: "RD Congo",
    apiHomeTeam: "Portugal",
    apiAwayTeam: "Congo DR",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  },
  {
    id: "inghilterra-croazia",
    homeTeam: "Inghilterra",
    awayTeam: "Croazia",
    apiHomeTeam: "England",
    apiAwayTeam: "Croatia",
    apiFixtureId: null,
    realHomeScore: null,
    realAwayScore: null,
    finished: false
  }
];